// <auto-generated />
using System;
using System.Collections.Generic;
using LogicaAccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(EmpresaContexto))]
    partial class EmpresaContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.EntidadesNegocio.Caracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsUsado")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeCombustible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeDireccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UnicoDuenio")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("caracteristicas");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteCompraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublicacionCompradaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCompraId");

                    b.HasIndex("PublicacionCompradaId");

                    b.ToTable("compras");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("direcciones");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Maquinaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaracteristicaId")
                        .HasColumnType("int");

                    b.Property<int>("DireccionId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.ComplexProperty<Dictionary<string, object>>("OtrasCaracteristicas", "Dominio.EntidadesNegocio.Maquinaria.OtrasCaracteristicas#OtrasCaracteristicas", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CaracteristicasFaltantes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CaracteristicaId");

                    b.HasIndex("DireccionId");

                    b.ToTable("maquinarias");

                    b.HasDiscriminator().HasValue("Maquinaria");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteVendeId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDePublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnaMaquinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteVendeId");

                    b.HasIndex("UnaMaquinaId");

                    b.ToTable("publicaciones");

                    b.HasDiscriminator().HasValue("Publicacion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoDeRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Contrasenia", "Dominio.EntidadesNegocio.Usuario.Contrasenia#Contrasenia", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Pass")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Dominio.EntidadesNegocio.Usuario.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("EmailUsr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.CargadoraPala", b =>
                {
                    b.HasBaseType("Dominio.EntidadesNegocio.Maquinaria");

                    b.Property<int>("Cilindro")
                        .HasColumnType("int");

                    b.Property<string>("MarcaMotor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("maquinarias", t =>
                        {
                            t.Property("MarcaMotor")
                                .HasColumnName("CargadoraPala_MarcaMotor");
                        });

                    b.HasDiscriminator().HasValue("CargadoraPala");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Cosechadora", b =>
                {
                    b.HasBaseType("Dominio.EntidadesNegocio.Maquinaria");

                    b.Property<int>("CapacidadDeCarga")
                        .HasColumnType("int");

                    b.Property<bool>("EsRuedaDual")
                        .HasColumnType("bit");

                    b.Property<string>("TipoCosechadora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Cosechadora");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Fertilizadora", b =>
                {
                    b.HasBaseType("Dominio.EntidadesNegocio.Maquinaria");

                    b.Property<bool>("DobleTraccion")
                        .HasColumnType("bit");

                    b.Property<string>("MarcaMotor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Potencia")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Fertilizadora");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Sembradora", b =>
                {
                    b.HasBaseType("Dominio.EntidadesNegocio.Maquinaria");

                    b.Property<string>("TipoDeSembradora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Sembradora");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Tractor", b =>
                {
                    b.HasBaseType("Dominio.EntidadesNegocio.Maquinaria");

                    b.Property<bool>("TieneCabina")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Tractor");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Venta", b =>
                {
                    b.HasBaseType("Dominio.EntidadesNegocio.Publicacion");

                    b.Property<DateTime>("FechaPublicacionVenta")
                        .HasColumnType("datetime2");

                    b.Property<double>("PrecioVenta")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Venta");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Administrador", b =>
                {
                    b.HasBaseType("Dominio.EntidadesNegocio.Usuario");

                    b.Property<string>("Apodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Cliente", b =>
                {
                    b.HasBaseType("Dominio.EntidadesNegocio.Usuario");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty<Dictionary<string, object>>("Telefono", "Dominio.EntidadesNegocio.Cliente.Telefono#Telefono", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Tel")
                                .HasColumnType("int");
                        });

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Compra", b =>
                {
                    b.HasOne("Dominio.EntidadesNegocio.Cliente", "ClienteCompra")
                        .WithMany()
                        .HasForeignKey("ClienteCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.EntidadesNegocio.Publicacion", "PublicacionComprada")
                        .WithMany()
                        .HasForeignKey("PublicacionCompradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteCompra");

                    b.Navigation("PublicacionComprada");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Maquinaria", b =>
                {
                    b.HasOne("Dominio.EntidadesNegocio.Caracteristica", "Caracteristica")
                        .WithMany()
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.EntidadesNegocio.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Publicacion", b =>
                {
                    b.HasOne("Dominio.EntidadesNegocio.Cliente", "ClienteVende")
                        .WithMany()
                        .HasForeignKey("ClienteVendeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.EntidadesNegocio.Maquinaria", "UnaMaquina")
                        .WithMany()
                        .HasForeignKey("UnaMaquinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteVende");

                    b.Navigation("UnaMaquina");
                });

            modelBuilder.Entity("Dominio.EntidadesNegocio.Usuario", b =>
                {
                    b.HasOne("Dominio.EntidadesNegocio.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
